## this is a sample kubernetes secret containing all the sensitive information
## required to connect to your kafka services
##
## You can apply this with
## kubectl apply -f sample-secrets.yaml
##

apiVersion: v1
kind: Secret
metadata:
  name: cloud-kafka
  namespace: ashkal
type: Opaque
data:
  CLUSTER_API_KEY: your base64 encoded secret here 
  CLUSTER_API_SECRET: your base64 encoded secret here
  SR_API_KEY: your base64 encoded secret here
  SR_API_SECRET: your base64 encoded secret here
  