apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }} 
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ .Values.service.name }}        
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
{{- with .Values.data }}
data:
{{- toYaml . | nindent 2 }}
{{- end }}